# Generated by Django 3.1.1 on 2020-09-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailto', models.CharField(choices=[('GO', 'Gina Gonzo'), ('RT', 'Rob Turn'), ('SS', 'Steven Smith'), ('MM', 'Mary Mag')], default='GO', max_length=2, verbose_name='Send mail to')),
                ('subject', models.CharField(max_length=150)),
                ('mail_date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymessapp.person')),
            ],
        ),
    ]
